CREATE TABLE usuario (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(160)  NOT NULL,
    senha_hash           VARCHAR(72)   NOT NULL,
    nome_estabelecimento VARCHAR(120)  NOT NULL,
    criado_em            TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE cobranca (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                        VARCHAR(40)  NOT NULL,
    usuario_id                    BIGINT       NOT NULL,
    valor_em_centavos             BIGINT       NOT NULL,
    valor_estornado_em_centavos   BIGINT       NOT NULL DEFAULT 0,
    moeda                         VARCHAR(3)   NOT NULL,
    descricao                     VARCHAR(140) NOT NULL,
    metodo                        VARCHAR(20)  NOT NULL,
    status                        VARCHAR(25)  NOT NULL,
    motivo_recusa                 VARCHAR(30),
    codigo_autorizacao            VARCHAR(12),
    captura_automatica            BOOLEAN      NOT NULL,
    bandeira                      VARCHAR(15),
    bin                           VARCHAR(6),
    ultimos_quatro                VARCHAR(4),
    nome_portador                 VARCHAR(120),
    chave_idempotencia            VARCHAR(80),
    criado_em                     TIMESTAMP(6) NOT NULL,
    atualizado_em                 TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_cobranca_codigo UNIQUE (codigo),
    CONSTRAINT uk_cobranca_idempotencia UNIQUE (usuario_id, chave_idempotencia),
    CONSTRAINT fk_cobranca_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_cobranca_usuario_criado_em ON cobranca (usuario_id, criado_em);
CREATE INDEX ix_cobranca_usuario_status ON cobranca (usuario_id, status);

CREATE TABLE estorno (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(40)  NOT NULL,
    cobranca_id       BIGINT       NOT NULL,
    valor_em_centavos BIGINT       NOT NULL,
    motivo            VARCHAR(140),
    criado_em         TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_estorno_codigo UNIQUE (codigo),
    CONSTRAINT fk_estorno_cobranca FOREIGN KEY (cobranca_id) REFERENCES cobranca (id)
);

CREATE INDEX ix_estorno_cobranca ON estorno (cobranca_id);

CREATE TABLE evento_cobranca (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cobranca_id     BIGINT       NOT NULL,
    tipo            VARCHAR(30)  NOT NULL,
    status_anterior VARCHAR(25),
    status_novo     VARCHAR(25)  NOT NULL,
    detalhe         VARCHAR(200),
    criado_em       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_evento_cobranca FOREIGN KEY (cobranca_id) REFERENCES cobranca (id)
);

CREATE INDEX ix_evento_cobranca ON evento_cobranca (cobranca_id, criado_em);
