-- Endpoint que o estabelecimento cadastra para receber os eventos.
CREATE TABLE endpoint_webhook (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(40)  NOT NULL,
    usuario_id  BIGINT       NOT NULL,
    url         VARCHAR(300) NOT NULL,
    segredo     VARCHAR(80)  NOT NULL,
    descricao   VARCHAR(120),
    ativo       BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_endpoint_codigo UNIQUE (codigo),
    CONSTRAINT fk_endpoint_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_endpoint_usuario ON endpoint_webhook (usuario_id);

-- Caixa de saida: a entrega nasce na mesma transacao que muda a cobranca, e
-- so depois sai pela rede. Se o processo cair no meio, a linha continua aqui.
CREATE TABLE entrega_webhook (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(40)   NOT NULL,
    endpoint_id         BIGINT        NOT NULL,
    evento              VARCHAR(40)   NOT NULL,
    corpo               VARCHAR(4000) NOT NULL,
    situacao            VARCHAR(20)   NOT NULL,
    tentativas          INTEGER       NOT NULL DEFAULT 0,
    ultimo_codigo_http  INTEGER,
    ultima_falha        VARCHAR(300),
    proxima_tentativa_em TIMESTAMP(6),
    criado_em           TIMESTAMP(6)  NOT NULL,
    concluido_em        TIMESTAMP(6),
    CONSTRAINT uk_entrega_codigo UNIQUE (codigo),
    CONSTRAINT fk_entrega_endpoint FOREIGN KEY (endpoint_id) REFERENCES endpoint_webhook (id)
);

-- O entregador varre exatamente por esta combinacao a cada rodada.
CREATE INDEX ix_entrega_pendente ON entrega_webhook (situacao, proxima_tentativa_em);
CREATE INDEX ix_entrega_endpoint ON entrega_webhook (endpoint_id, criado_em);
