CREATE TABLE link_pagamento (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                VARCHAR(40)  NOT NULL,
    usuario_id            BIGINT       NOT NULL,
    descricao             VARCHAR(140) NOT NULL,
    valor_em_centavos     BIGINT       NOT NULL,
    metodo                VARCHAR(20)  NOT NULL,
    parcelas_maximas      INTEGER      NOT NULL DEFAULT 1,
    limite_de_usos        INTEGER,
    usos                  INTEGER      NOT NULL DEFAULT 0,
    ativo                 BOOLEAN      NOT NULL DEFAULT TRUE,
    expira_em             TIMESTAMP(6),
    criado_em             TIMESTAMP(6) NOT NULL,
    atualizado_em         TIMESTAMP(6) NOT NULL,
    versao                BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uk_link_pagamento_codigo UNIQUE (codigo),
    CONSTRAINT fk_link_pagamento_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id),
    CONSTRAINT ck_link_pagamento_valor CHECK (valor_em_centavos > 0),
    CONSTRAINT ck_link_pagamento_parcelas CHECK (parcelas_maximas BETWEEN 1 AND 12),
    CONSTRAINT ck_link_pagamento_limite CHECK (limite_de_usos IS NULL OR limite_de_usos > 0),
    CONSTRAINT ck_link_pagamento_usos CHECK (usos >= 0)
);

CREATE INDEX ix_link_pagamento_usuario_criado
    ON link_pagamento (usuario_id, criado_em);

ALTER TABLE cobranca ADD COLUMN link_pagamento_id BIGINT;
ALTER TABLE cobranca ADD CONSTRAINT fk_cobranca_link_pagamento
    FOREIGN KEY (link_pagamento_id) REFERENCES link_pagamento (id);

CREATE INDEX ix_cobranca_link_criado
    ON cobranca (link_pagamento_id, criado_em);

-- Cobrem os filtros mais usados do razao sem abandonar a ordenacao temporal.
CREATE INDEX ix_cobranca_usuario_status_criado
    ON cobranca (usuario_id, status, criado_em);
CREATE INDEX ix_cobranca_usuario_metodo_criado
    ON cobranca (usuario_id, metodo, criado_em);
